scrapeInterval: "300s"
nameOverride: ""
grafana:
  adminUsername: "admin"
  uri: ""
  domain: ""
  dashboards:
    feEnabled: "false"
    nodeExporterEnabled: "false"
    rempEnabled: "false"
    systemEnabled: "false"
    telegramEnabled: "false"
    wpEnabled: "false"
pushgw:
  domain: ""
  uri: ""
  ingressUri: ""
loki:
  enabled: true
  domain: ""
  ingressUri: ""
  storage: 3Gi
prometheus:
  rulesSystem:
    enabled: true
    enableCertificateExpirySoon: true
    enableHeartBeat: true
    enableDiskUsage: true
    enableNoSWAP: true
    enableHighSwapUsage: true
    enableContainerDown: true
    enableElasticSearchIndices: true
    enableLokiErrors: true
    enableLokiHighErrors: true
  extraRules: {}
blackbox:
#  google:
#    url: https://google.com
#    module: http_2xx | https_probe
#mail:
#  username: "user@mail.domain.com"
#  sender: "user@mail.domain.com"
#  url: "mail.domain.com:587"
#  receiver: "user@mail.domain.com"

# we support two types, secrets in this values.yaml
# but safe way is using Hashicorp Vault
secrets:
#  type: vault
#  vaultUrl: "http://sys-vault.sys-vault.svc.cluster.local:8200"
#  vaultPath: "secrets/monitoring"
#  tokenName: vault-{{ .Values.nameOverride }}-token

#  type: helm
#  slackWebHook: ""
#  grafanaAdminPassword: ""
#  grafanaClientSecret: ""
#  grafanaAllowedDomains: "grafana.com"
#  thanosS3Bucket: ""
#  thanosS3Endpoint: ""
#  thanosS3AccessKey: ""
#  thanosS3SecretKey: ""
#  mailPassword: ""
#  pushGwAuth: ""
#  lokiAuth: ""
#  lokiS3Endpoint: ""
#  lokiS3AccessKey: ""
#  lokiS3SecretKey: ""

extraObjects: []