nameOverride: ""
grafana:
  adminPassword: ""
  adminUsername: ""
  allowedDomains: ""
  clientId: ""
  clientSecret: ""
  uri: ""
  domain: ""
pushgw:
  domain: ""
  uri: ""
  auth: ""
prometheus:
  rulesSystemEnabled: false
  rulesRempEnabled: false
blackbox:
#  google:
#    url: https://google.com