nameOverride: ""
slackWebHook: ""
grafana:
  adminPassword: ""
  adminUsername: ""
  allowedDomains: ""
  clientId: ""
  clientSecret: ""
  uri: ""
  domain: ""
  dashboard: "system"
pushgw:
  domain: ""
  uri: ""
  auth: ""
prometheus:
  rulesSystemEnabled: false
  rulesRempEnabled: false
blackbox:
#  google:
#    url: https://google.com
#    module: http_2xx | https_probe
#mail:
#  username: "user@mail.domain.com"
#  password: "five-stars"
#  sender: "user@mail.domain.com"
#  url: "mail.domain.com:587"
#  receiver: "user@mail.domain.com"