scrapeInterval: "300s"
nameOverride: ""
grafana:
  adminUsername: ""
  allowedDomains: ""
  clientId: ""
  uri: ""
  domain: ""
  dashboard: "system"
pushgw:
  domain: ""
  uri: ""
#thanos:
#  s3Bucket: bucket-name
#  s3AccessKey: ASDF
#  s3Endpoint: "s3.com"
prometheus:
  rulesSystem:
    enabled: true
    enableCertificateExpirySoon: true
    enableHeartBeat: true
    enableDiskUsage: true
    enableNoSWAP: true
    enableHighSwapUsage: true
    enableContainerDown: true
    enableElasticSearchIndices: true
blackbox:
#  google:
#    url: https://google.com
#    module: http_2xx | https_probe
#mail:
#  username: "user@mail.domain.com"
#  sender: "user@mail.domain.com"
#  url: "mail.domain.com:587"
#  receiver: "user@mail.domain.com"

# we support two types, secrets in this values.yaml
# but safe way is using Hashicorp Vault
secrets:

#  type: vault

  type: helm
  slackWebHook: ""
  grafanaAdminPassword: ""
  grafanaClientSecret: ""
  thanosS3SecretKey: ""
  mailPassword: ""
  pushGwAuth: ""