{
 "title": "Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(conveior_dockerContainer{entity=\"$entity\"}, label_name)"
    }
   },
   {
    "name": "url",
    "query": {
     "query": "label_values(probe_success{prometheus=\"$entity/$entity\"}, instance)"
    }
   },
   {
    "name": "loki_file_crm",
    "label": "loki_file_crm",
    "query": {}
   },
   {
    "name": "loki_file_remp_beam",
    "label": "loki_file_remp_beam",
    "query": {}
   },
   {
    "name": "loki_file_remp_campaign",
    "label": "loki_file_remp_campaign",
    "query": {}
   },
   {
    "name": "loki_file_remp_mailer",
    "label": "loki_file_remp_mailer",
    "query": {}
   },
   {
    "name": "entity",
    "label": "entity",
    "query": {
     "query": "label_values(conveior_hwCpu,entity)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "repeat": "container",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_dockerContainer{entity=\"$entity\",label_name=\"$container\"}[300s]",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 2 },
   "repeat": "url",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$url\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Business - overall data (beta testing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payments in 12 months [in EUR]",
     "type": "barchart",
     "description": "Payments in 12 months [in EUR]",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentYear\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Total payments in last 30 days [in EUR]",
     "type": "barchart",
     "description": "Total payments in last 30 days [in EUR]",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 4 },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentMonth\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Successful payments last 7 days",
     "type": "barchart",
     "description": "Successful payments last 7 days",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentWeekFailed\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Successful payments last 24 hours",
     "type": "barchart",
     "description": "Successful payments last 24 hours",
     "gridPos": { "h": 5, "w": 14, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentDayFailed\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Successful payments last hour",
     "type": "barchart",
     "description": "Successful payments last hour",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentHourFailed\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Successful payments on gateway last 7 days",
     "type": "barchart",
     "description": "Successful payments on gateway last 7 days",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentGatewayWeekFailed\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Successful payments on gateway last 24 hours",
     "type": "barchart",
     "description": "Successful payments on gateway last 24 hours",
     "gridPos": { "h": 5, "w": 14, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentGatewayDayFailed\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Succ. payments on gw last hour",
     "type": "barchart",
     "description": "Succ. payments on gw last hour",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlPaymentGatewayHourFailed\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Mail queue (s)",
     "type": "barchart",
     "description": "Mail queue (s)",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_sqlMailQueing\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Successful login attempts",
     "type": "barchart",
     "description": "Successful login attempts",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_loginAttempts\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Business - Users (beta testing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users in last 12 months",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "conveior_sql_query{query_name=\"conveior_sqlUserYear\",entity=\"$entity\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Users in last 30 days",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_sqlUserMonth\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Payments in 5 minutes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "conveior_sql_query{query_name=\"conveior_sqlPayment5m\",entity=\"$entity\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  { "title": "HW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "stat",
   "description": "CPU load average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwCpu{entity=\"$entity\"}[300s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "RAM load average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwRam{entity=\"$entity\",label_name=\"used\"}[300s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "stat",
   "description": "SWAP load average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwSwap{entity=\"$entity\",label_name=\"used\"}[300s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "description": "Disk usage average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwDisk{entity=\"$entity\",label_name=\"overlay\"}[300s]",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "CPU usage",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "conveior_hwCpu{entity=\"$entity\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "RAM total/used",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "conveior_hwRam{entity=\"$entity\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "SWAP total/used",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "conveior_hwSwap{entity=\"$entity\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Disk used",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "conveior_hwDisk{entity=\"$entity\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "HW details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU per process > 10 %",
     "type": "stat",
     "description": "CPU load per process in selected time frame.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_hwCpuProcess{entity=\"$entity\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "RAM per process > 10 %",
     "type": "stat",
     "description": "RAM load per process in selected time frame.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_hwRamProcess{entity=\"$entity\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "stat",
     "description": "Processes count in last 5 minutes",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_hwProcess{entity=\"$entity\",label_name=\"conveior\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Boot time",
     "type": "stat",
     "description": "Boot time",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_hwBoot{entity=\"$entity\"}[300s]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "CPU usage per process > 10%",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_hwCpuProcess{entity=\"$entity\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "RAM total/used per process > 10",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "conveior_hwRamProcess{entity=\"$entity\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "conveior_hwProcess{entity=\"$entity\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "SQL global_wait_timeout",
     "type": "stat",
     "description": "SQL wait_timeout",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_global_wait_timeout\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "SQL global_interactive_timeout",
     "type": "stat",
     "description": "SQL global_interactive_timeout",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_global_interactive_timeout\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "SQL local_wait_timeout",
     "type": "stat",
     "description": "SQL local_wait_timeout",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_local_wait_timeout\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "SQL local_interactive_timeout",
     "type": "stat",
     "description": "SQL local_interactive_timeout",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_local_interactive_timeout\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Sleeper SQL processes",
     "type": "stat",
     "description": "Sleeper SQL processes count in last 5 minutes",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(conveior_sql_query{entity=\"$entity\",query_name=\"conveior_sqlSleeperProcess\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Containers size",
     "type": "stat",
     "description": "Sum of size of containers in last 5 minutes",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(conveior_hwDockerSize{entity=\"$entity\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "stat",
     "description": "Sum of network load of all containers in last 5 minutes",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(conveior_hwNetwork{entity=\"$entity\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Elasticsearch health",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_elasticsearch{entity=\"$entity\"}[300s]",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Containers",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_sqlSleeperProcess\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Containers",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "conveior_hwDockerSize{entity=\"$entity\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Network usage",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "conveior_hwNetwork{entity=\"$entity\",query_name=\"tx\"}",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "conveior_hwNetwork{entity=\"$entity\",query_name=\"rx\"}*(-1)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "conveior_elasticsearch{entity=\"$entity\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Containers, Database tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Containers start up time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "conveior_hwDockerLs{entity=\"$entity\"}*1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Containers size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "conveior_hwDockerSize{entity=\"$entity\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "top 10 containers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,conveior_hwDockerSize{entity=\"$entity\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Volumes size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "conveior_hwDockerVolumeSize{entity=\"$entity\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "top 10 volumes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,conveior_hwDockerVolumeSize{entity=\"$entity\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "conveior_hwHeartbeat{entity=\"$entity\"}*1000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "20 biggest DB tables",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, conveior_sql_query{entity=\"$entity\", query_name=\"conveior_dbSize\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "top 10 DB tables",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, conveior_sql_query{entity=\"$entity\", query_name=\"conveior_dbSize\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Logs: crm-crm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "loki",
   "collapsed": true,
   "panels": [
    {
     "title": "Logs: $loki_file_crm",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "repeat": "loki_file",
     "targets": [
      {
       "expr": "{job=\"crm-crm\", filename=~\"$loki_file_crm\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs: remp-beam",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs: $loki_file_remp_beam",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "repeat": "loki_file_remp_beam",
     "targets": [
      {
       "expr": "{job=\"remp-beam\", filename=~\"$loki_file_remp_beam\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs: remp-campaign",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs: $loki_file_remp_campaign",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "{job=\"remp-campaign\", filename=~\"$loki_file_remp_beam\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs: remp-mailer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs: $loki_file_remp_mailer",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "{job=\"remp-mailer\", filename=~\"$loki_file_remp_beam\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}