apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: alertmanager
    app.kubernetes.io/instance: {{ include "helmMonitorie.name" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ include "helmMonitorie.name" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    argocd.argoproj.io/instance: {{ include "helmMonitorie.name" . }}
    chart: {{ include "helmMonitorie.name" . }}-{{ .Chart.Version }}
    heritage: Helm
    release: {{ include "helmMonitorie.name" . }}
  name: alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector: {}
  externalUrl: 'http://alertmanager.{{ .Release.Namespace }}:9093'
  image: 'quay.io/prometheus/alertmanager:v0.25.0'
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: http-web
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager
  version: v0.25.0
