apiVersion: v1
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: {{ .Values.slackWebHook }}
    inhibit_rules:
    - equal:
      - namespace
      - alertname
      source_matchers:
      - severity = critical
      target_matchers:
      - severity =~ warning|info
    - equal:
      - namespace
      - alertname
      source_matchers:
      - severity = warning
      target_matchers:
      - severity = info
    - equal:
      - namespace
      source_matchers:
      - alertname = InfoInhibitor
      target_matchers:
      - severity = info
    receivers:
    - name: "null"
    - name: slack
      slack_configs:
      - channel: '{{ .Values.slackChannel }}'
        send_resolved: true
        text: '{{ "{{" }} template "slack.default.text" . }}'
        title: Monitoring [{{ "{{" }} .Status | toUpper }}{{ "{{" }} if eq .Status "firing" }}{{ "{{" }} .Alerts.Firing | len }} event(s){{ "{{" }} end }}]
    - name: mail
      email_configs:
      - auth_identity: {{ .Values.mail.username }}
        auth_password: {{ .Values.mail.password }}
        auth_username: {{ .Values.mail.username }}
        from: {{ .Values.mail.sender }}
        send_resolved: true
        smarthost: {{ .Values.mail.url }}
        to: {{ .Values.mail.receiver }} 
    route:
      group_by:
      - alertname
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
      - matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
        receiver: "null"
      - continue: true
        matchers:
        - severity =~ "critical|high|error|warning"
        receiver: slack
      - continue: true
        matchers:
        - severity =~ "critical|high|error|warning"
        receiver: mail
    templates:
    - /etc/alertmanager/config/*.tmpl
  slack.tmpl: |-
    {{ "{{" }} define "cluster" }}{{ "{{" }} .ExternalURL | reReplaceAll ".*alertmanager\\.(.*)" "$1" }}{{ "{{" }} end }}
    {{ "{{" }} define "slack.default.text" }}
    {{ "{{" }}- $root := . -}}
    {{ "{{" }} range .Alerts }}
      `{{ "{{" }} .Labels.severity }}` *{{ "{{" }} .Annotations.summary }}*
      *Details:*
         - Alertname: `{{ "{{" }} .Labels.alertname }}`
         - Entity: `{{ "{{" }} .Labels.entity }}`
         - Label_name: `{{ "{{" }} .Labels.label_name }}`
         - Severity: `{{ "{{" }} .Labels.severity }}`
    {{ "{{" }} end }}
    {{ "{{" }} end }}
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ include "helmMonitorie.name" . }}-alertmanager
    app.kubernetes.io/instance: {{ include "helmMonitorie.name" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ include "helmMonitorie.name" . }}
    argocd.argoproj.io/instance: sys-monitoring
    release: {{ include "helmMonitorie.name" . }}
  name: alertmanager-{{ include "helmMonitorie.name" . }}
  namespace: {{ .Release.Namespace }}
