apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-template
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  slack.tmpl: |-
    {{ "{{" }} define "cluster" }}{{ "{{" }} .ExternalURL | reReplaceAll ".*alertmanager\\.(.*)" "$1" }}{{ "{{" }} end }}
    {{ "{{" }} define "slack.default.text" }}
    {{ "{{" }}- $root := . -}}
    {{ "{{" }} range .Alerts }}
      `{{ "{{" }} .Labels.alertname }}/{{ "{{" }} .Labels.label_name }}/{{ "{{" }} .Labels.severity }}` *{{ "{{" }} .Annotations.summary }}*
    {{ "{{" }} end }}
    {{ "{{" }} end }}