apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blackbox
  name: blackbox
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: blackbox
      app.kubernetes.io/name: blackbox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: blackbox
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: blackbox
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - '--config.file=/config/blackbox.yaml'
          env: null
          image: 'prom/blackbox-exporter:v0.22.0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: blackbox-exporter
          ports:
            - containerPort: 9115
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 30m
              memory: 30Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /config
              name: config
      hostNetwork: false
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: blackbox
      volumes:
        - configMap:
            name: blackbox
          name: config
