apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blackbox
    argocd.argoproj.io/instance: blackbox
    helm.sh/chart: {{ include "helmMonitorie.name" . }}-{{ .Chart.Version }}
  name: blackbox
  namespace: {{ .Release.Namespace }}
