apiVersion: v1
data:
  blackbox.yaml: |
    modules:
      https_probe:
        prober: http
        timeout: 10s
        http:
          method: GET
          valid_http_versions: [HTTP/1.1, HTTP/2]
          valid_status_codes: []
          tls_config:
            insecure_skip_verify: false
      http_2xx:
        http:
          follow_redirects: true
          valid_http_versions: [HTTP/1.1, HTTP/2]
          valid_status_codes: []
          method: GET
          headers:
            Host: ""
          fail_if_ssl: false
        prober: http
        timeout: 5s
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blackbox
  name: blackbox
  namespace: {{ .Release.Namespace }}
