apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: sys-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 43.2.1
    argocd.argoproj.io/instance: sys-monitoring
    release: sys-monitoring
  name: sys-monitoring-kube-promet-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: sys-monitoring-kube-promet-alertmanager
        namespace: sys-monitoring
        pathPrefix: /
        port: http-web
  enableAdminAPI: false
  externalLabels:
    datacenter: fcm
  externalUrl: 'http://sys-monitoring-kube-promet-prometheus.sys-monitoring:9090'
  hostNetwork: false
  image: 'quay.io/prometheus/prometheus:v2.40.5'
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: sys-monitoring
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: sys-monitoring
  replicas: 1
  resources:
    limits:
      cpu: 600m
      memory: 1000Mi
    requests:
      cpu: 250m
      memory: 400Mi
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: sys-monitoring
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: sys-monitoring-kube-promet-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: sys-monitoring
  shards: 1
  thanos:
    image: 'quay.io/thanos/thanos:v0.32.2'
    objectStorageConfig:
      key: objstore.yml
      name: thanos-objectstorage
  version: v2.40.5
  walCompression: false
