---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.grafana.domain }}`) && PathPrefix(`/{{ .Values.grafana.uri }}`)
      middlewares:
        - name: grafana
          namespace: {{ .Release.Namespace }}
      services:
        - name: grafana
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /{{ .Values.grafana.uri }}