apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-user-creation-script
  namespace: {{ .Release.Namespace }}
data:
  create-users.sh: |
    #!/bin/sh
    echo "Checking for the existence of the secret..."
    if [ -f /etc/grafana-users-secret/GRAFANA_USERS ]; then
      echo "Secret exists. Proceeding to create users..."
      USERS=$(cat /etc/grafana-users-secret/GRAFANA_USERS)
      echo "Waiting for Grafana to be ready..."
      RETRIES=0
      until curl --fail --silent http://localhost:3000/api/health; do
        RETRIES=$((RETRIES+1))
        if [ $RETRIES -ge 30 ]; then
          echo "Grafana is not ready after multiple attempts. Continuing to wait..."
          sleep 5
          continue
        fi
        sleep 5
      done
      echo "Grafana is ready. Creating users..."
      sleep 10
      for user in $(echo $USERS | jq -c '.[]'); do
        name=$(echo $user | jq -r '.name')
        email=$(echo $user | jq -r '.email')
        password=$(echo $user | jq -r '.password')
        role=$(echo $user | jq -r '.role')
        
        echo "Checking if user $name exists..."
        EXISTING_USER=$(curl -s -X GET http://$GF_SECURITY_ADMIN_USER:$GF_SECURITY_ADMIN_PASSWORD@localhost:3000/api/users/lookup?loginOrEmail=$email)
        EXISTING_USER_ID=$(echo $EXISTING_USER | jq -r '.id')
        
        if [ "$EXISTING_USER_ID" != "null" ]; then
          echo "User $name already exists with ID $EXISTING_USER_ID. Updating role to $role."
          if ! curl -X PATCH http://$GF_SECURITY_ADMIN_USER:$GF_SECURITY_ADMIN_PASSWORD@localhost:3000/api/orgs/1/users/$EXISTING_USER_ID -H "Content-Type: application/json" -d "{\"role\":\"$role\"}"; then
            echo "Failed to update role for user $name"
          fi
        else
          echo "Creating user $name with role $role"
          USER_RESPONSE=$(curl -s -X POST http://$GF_SECURITY_ADMIN_USER:$GF_SECURITY_ADMIN_PASSWORD@localhost:3000/api/admin/users -H "Content-Type: application/json" -d "{\"name\":\"$name\",\"email\":\"$email\",\"login\":\"$name\",\"password\":\"$password\"}")
          USER_ID=$(echo $USER_RESPONSE | jq -r '.id')
          echo "USER_ID: $USER_ID"
          if [ "$USER_ID" != "null" ]; then
            echo "Setting role for user $name to $role"
            if ! curl -X PATCH http://$GF_SECURITY_ADMIN_USER:$GF_SECURITY_ADMIN_PASSWORD@localhost:3000/api/orgs/1/users/$USER_ID -H "Content-Type: application/json" -d "{\"role\":\"$role\"}"; then
              echo "Failed to set role for user $name"
            fi
          else
            echo "Failed to create user $name"
          fi
        fi
      done
    else
      echo "Secret does not exist. Skipping user creation."
    fi
    echo "User creation script completed. Sleeping indefinitely..."
    sleep infinity
