apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      name: Thanos
      type: prometheus
      uid: P5DCFC7561CCDE821
      url: http://thanos-query.{{ .Release.Namespace }}:9090

kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    argocd.argoproj.io/instance: grafana
  name: grafana
  namespace: {{ .Release.Namespace }}
