apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      name: Thanos
      type: prometheus
      uid: P5DCFC7561CCDE821
      url: http://thanos-query.{{ .Release.Namespace }}:9090
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth.google]
    allow_sign_up = true
    allowed_domains = {{ .Values.grafana.allowedDomains }}
    api_url = https://www.googleapis.com/oauth2/v1/userinfo
    auth_url = https://accounts.google.com/o/oauth2/auth
    client_id = {{ .Values.grafana.clientId }}
    client_secret = {{ .Values.grafana.clientSecret }}
    enabled = true
    scopes = https://www.googleapis.com/auth/userinfo.profile
    https://www.googleapis.com/auth/userinfo.email
    token_url = https://accounts.google.com/o/oauth2/token
    [dashboards]
    default_home_dashboard_path = /etc/grafana/provisioning/dashboards/default.json
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = localhost
    root_url = https://{{ .Values.grafana.domain }}{{ .Values.grafana.uri }}
    [users]
    default_theme = light
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: {{ .Chart.Version }}
    argocd.argoproj.io/instance: grafana
    helm.sh/chart: {{ include "helmMonitorie.name" . }}-{{ .Chart.Version }}
  name: grafana
  namespace: {{ .Release.Namespace }}
