apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        checksum-config: {{ include (print $.Template.BasePath "/secret.yml") . | sha256sum | trimSuffix "-" | trunc 63 }}
        checksum-config-datasource: {{ include (print $.Template.BasePath "/grafana-datasource.yml") . | sha256sum | trimSuffix "-" | trunc 63 }}
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/name: grafana
    spec:
      automountServiceAccountToken: true
      initContainers:
        - name: create-grafana-users
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking for the existence of the secret..."
              if [ -f /etc/grafana-users-secret/GRAFANA_USERS ]; then
                echo "Secret exists. Proceeding to create users..."
                USERS=$(cat /etc/grafana-users-secret/GRAFANA_USERS | base64 --decode)
                echo "Waiting for Grafana to be ready..."
                until curl --fail --silent http://localhost:3000/api/health; do
                  sleep 5
                done
                echo "Grafana is ready. Creating users..."
                for user in $(echo $USERS | jq -c '.[]'); do
                  name=$(echo $user | jq -r '.name')
                  email=$(echo $user | jq -r '.email')
                  password=$(echo $user | jq -r '.password')
                  role=$(echo $user | jq -r '.role')
                  echo "Creating user $name with role $role"
                  USER_RESPONSE=$(curl -XPOST http://admin:admin@localhost:3000/api/admin/users -H "Content-Type: application/json" -d "{\"name\":\"$name\",\"email\":\"$email\",\"login\":\"$name\",\"password\":\"$password\"}")
                  USER_ID=$(echo $USER_RESPONSE | grep -o '"id":[0-9]*' | grep -o '[0-9]*')
                  echo "Setting role for user $name to $role"
                  curl -XPUT http://admin:admin@localhost:3000/api/orgs/1/users/${USER_ID} -H "Content-Type: application/json" -d "{\"role\":\"$role\"}"
                done
              else
                echo "Secret does not exist. Skipping user creation."
              fi
          volumeMounts:
            - name: grafana-users-secret
              mountPath: /etc/grafana-users-secret
              readOnly: true
      containers:
        - env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUsername }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_PATHS_DATA
              value: /var/lib/grafana/
            - name: GF_PATHS_LOGS
              value: /var/log/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          image: 'grafana/grafana:10.4.3'
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
          resources:
            limits:
              memory: 150Mi
            requests:
              cpu: 30m
              memory: 30Mi
          volumeMounts:
            - mountPath: /etc/grafana
              name: grafana-ini
            - mountPath: /etc/grafana/provisioning/datasources/
              name: grafana-datasource
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards/
      enableServiceLinks: true
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
      serviceAccountName: grafana
      volumes:
        - configMap:
            name: grafana
          name: grafana
        - name: grafana-ini
          secret:
            secretName: secret
            items:
              - key: "grafana.ini"
                path: "grafana.ini"
        - name: grafana-datasource
          secret:
            secretName: grafana-datasource
            items:
              - key: "datasources.yaml"
                path: "datasources.yaml"
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
{{- if or (eq .Values.grafana.dashboards.feEnabled "default") (eq .Values.grafana.dashboards.feEnabled "true") }}
              - key: dashboard-fe.json
                path: {{- if eq .Values.grafana.dashboards.feEnabled "default" }} default.json{{ else }} dashboard-fe.json{{ end }}
{{ end }}
{{- if or (eq .Values.grafana.dashboards.nodeExporterEnabled "default") (eq .Values.grafana.dashboards.nodeExporterEnabled "true") }}
              - key: dashboard-node-exporter.json
                path: {{- if eq .Values.grafana.dashboards.nodeExporterEnabled "default" }} default.json{{ else }} dashboard-node-exporter.json{{ end }}
{{ end }}
{{- if or (eq .Values.grafana.dashboards.rempEnabled "default") (eq .Values.grafana.dashboards.rempEnabled "true") }}
              - key: dashboard-remp.json
                path: {{- if eq .Values.grafana.dashboards.rempEnabled "default" }} default.json{{ else }} dashboard-remp.json{{ end }}
{{ end }}
{{- if or (eq .Values.grafana.dashboards.systemEnabled "default") (eq .Values.grafana.dashboards.systemEnabled "true") }}
              - key: dashboard-system.json
                path: {{- if eq .Values.grafana.dashboards.systemEnabled "default" }} default.json{{ else }} dashboard-system.json{{ end }}
{{ end }}
{{- if or (eq .Values.grafana.dashboards.telegramEnabled "default") (eq .Values.grafana.dashboards.telegramEnabled "true") }}
              - key: dashboard-telegram.json
                path: {{- if eq .Values.grafana.dashboards.telegramEnabled "default" }} default.json{{ else }} dashboard-telegram.json{{ end }}
{{ end }}
{{- if or (eq .Values.grafana.dashboards.wpEnabled "default") (eq .Values.grafana.dashboards.wpEnabled "true") }}
              - key: dashboard-wp.json
                path: {{- if eq .Values.grafana.dashboards.wpEnabled "default" }} default.json{{ else }} dashboard-wp.json{{ end }}
{{ end }}
        - name: grafana-users-secret
          secret:
            secretName: grafana-users-secret
