{{ if eq .Values.loki.enabled true -}}
  {{ if .Values.loki.ingressUri -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: secret-loki
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.loki.domain }}
      http:
        paths:
          - backend:
              service:
                name: loki
                port:
                  number: 3100
            path: /{{ .Values.loki.ingressUri }}(/|$)(.*)
            pathType: Prefix
  {{ else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: secret-loki
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  rules:
    - host: {{ .Values.loki.domain }}
      http:
        paths:
          - backend:
              service:
                name: loki
                port:
                  number: 3100
            path: /
            pathType: Prefix
  {{ end }}
{{ end }}
