{{ if eq .Values.loki.enabled true -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    auth_enabled: false
    common:
      path_prefix: {{ .Values.loki.path_prefix }}
      storage:
        s3:
          access_key_id: ${S3_LOKI_ACCESS_KEY_ID}
          bucketnames: loki-{{ include "helmMonitorie.name" . }}
          endpoint: ${S3_LOKI_ENDPOINT}
          insecure: false
          s3forcepathstyle: true
          secret_access_key: ${S3_LOKI_SECRET_ACCESS_KEY}
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    schema_config:
      configs:
      - from: "2022-01-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      aws:
        s3: s3://${S3_LOKI_ACCESS_KEY_ID}:${S3_LOKI_SECRET_ACCESS_KEY}@${S3_LOKI_ENDPOINT}/loki-{{ include "helmMonitorie.name" . }}
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/index_cache
        cache_ttl: 24h
        shared_store: s3
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
  {{ end }}
