{{ if eq .Values.loki.enabled true -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    auth_enabled: false
    common:
      compactor_address: '{{ include "helmMonitorie.name" . }}'
      path_prefix: /var/loki
      replication_factor: 1
    frontend:
      scheduler_address: ""
    frontend_worker:
      scheduler_address: ""
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
        - '127.0.0.1'
    query_range:
      align_queries_with_step: true
    ruler:
      alertmanager_url: http://alertmanager-operated:9093
      remote_write:
        client:
          url: http://prometheus:9090/api/v1/write
        enabled: true
      rule_path: /rules
      wal:
        dir: /tmp/ruler-wal
      storage:
        s3:
          access_key_id: ${S3_LOKI_ACCESS_KEY_ID}
          bucketnames: loki-{{ include "helmMonitorie.name" . }}
          endpoint: ${S3_LOKI_ENDPOINT}
          insecure: false
          s3forcepathstyle: true
          secret_access_key: ${S3_LOKI_SECRET_ACCESS_KEY}
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2022-01-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
{{ end }}