{{ if eq .Values.loki.enabled true -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: {{ .Release.Namespace }}
data:
  rules.yml: |
    groups:
    - name: recording-rules
      interval: 1m
      rules:
        - record: loki_error_rate
          expr: |
            sum(count_over_time({level="ERROR"}[1m]))
        - record: loki_rate
          expr: |
            sum(count_over_time({job=~".+"}[1m]))
  {{ end }}