{{ if eq .Values.loki.enabled true -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
  name: loki
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  type: ClusterIP
{{ end }}