{{ if eq .Values.loki.enabled true -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
  name: loki-memberlist
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp
      port: 7946
      protocol: TCP
      targetPort: http-memberlist
  selector:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  type: ClusterIP
{{ end }}