{{ if eq .Values.prometheus.rulesRempEnabled true -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: {{ include "helmMonitorie.name" . }}-prometheus
    app.kubernetes.io/instance: {{ include "helmMonitorie.name" . }}
    app.kubernetes.io/part-of: {{ include "helmMonitorie.name" . }}
    release: {{ include "helmMonitorie.name" . }}
  name: rule-remp
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: dashboard
      rules:
        - alert: HeartBeat
          annotations:
            description: There are not any new metrics in monitoring for {{ include "helmMonitorie.name" . }}.
            summary: There are not any new metrics in monitoring for {{ include "helmMonitorie.name" . }}.
          expr: conveior_hwHeartbeat{entity="{{ include "helmMonitorie.name" . }}"} == conveior_hwHeartbeat{entity="{{ include "helmMonitorie.name" . }}"} offset 5m
          for: 15m
          labels:
            severity: warning
  {{ end }}
