apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus-{{ include "helmMonitorie.name" . }}
    app.kubernetes.io/name: prometheus-{{ include "helmMonitorie.name" . }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: {{ include "helmMonitorie.name" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ include "helmMonitorie.name" . }}
    release: {{ include "helmMonitorie.name" . }}