apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ include "helmMonitorie.name" . }}
    release: {{ include "helmMonitorie.name" . }}
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
    - name: http
      port: 10902
      targetPort: http
    - name: http-web
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: {{ include "helmMonitorie.name" . }}
  type: ClusterIP
