#apiVersion: monitoring.coreos.com/v1
#kind: Prometheus
#metadata:
#  labels:
#    app: {{ include "helmMonitorie.name" . }}-prometheus
#    app.kubernetes.io/instance: {{ include "helmMonitorie.name" . }}
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/part-of: {{ include "helmMonitorie.name" . }}
#    argocd.argoproj.io/instance: {{ include "helmMonitorie.name" . }}
#    heritage: Helm
#    release: {{ include "helmMonitorie.name" . }}
#  name: {{ include "helmMonitorie.name" . }}
#  namespace: {{ .Release.Namespace }}
#spec:
#  alerting:
#    alertmanagers:
#      - apiVersion: v2
#        name: alertmanager-operated
#        namespace: {{ .Release.Namespace }}
#        pathPrefix: /
#        port: http-web
#  enableAdminAPI: false
#  externalUrl: 'http://prometheus.{{ .Release.Namespace }}:9090'
#  hostNetwork: false
#  image: 'quay.io/prometheus/prometheus:v2.40.5'
#  listenLocal: false
#  logFormat: logfmt
#  logLevel: info
#  paused: false
#  podMonitorNamespaceSelector: {}
#  podMonitorSelector:
#    matchLabels:
#      release: {{ include "helmMonitorie.name" . }}
#  portName: http-web
#  probeNamespaceSelector: {}
#  probeSelector:
#    matchLabels:
#      release: {{ include "helmMonitorie.name" . }}
#  replicas: 1
#  resources:
#    limits:
#      cpu: 400m
#      memory: 400Mi
#    requests:
#      cpu: 30m
#      memory: 30Mi
#  retention: 10d
#  routePrefix: /
#  ruleNamespaceSelector: {}
#  ruleSelector:
#    matchLabels:
#      release: {{ include "helmMonitorie.name" . }}
#  securityContext:
#    fsGroup: 2000
#    runAsGroup: 2000
#    runAsNonRoot: true
#    runAsUser: 1000
#  serviceAccountName: prometheus
#  serviceMonitorNamespaceSelector: {}
#  serviceMonitorSelector:
#    matchLabels:
#      release: {{ include "helmMonitorie.name" . }}
#  shards: 1
#  thanos:
#    image: 'quay.io/thanos/thanos:v0.32.2'
#    objectStorageConfig:
#      key: objstore.yml
#      name: thanos-objectstorage
#  version: v2.40.5
#  walCompression: false
