{{ if eq .Values.prometheus.rulesSystem.enabled true -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rules
  namespace: {{ .Release.Namespace }}
data:
  rule-system.yaml: |-
    groups:
      - name: dashboard
        rules:
  {{- if .Values.prometheus.rulesSystem.enableCertificateExpirySoon }}
          - alert: CertificateExpirySoon
            expr: probe_ssl_earliest_cert_expiry - time() < 86400
            for: 10m
            labels:
              severity: critical
            annotations:
              title: "Certificate Expiry Alert"
              description: "The SSL certificate is expiring in less than 24 hours."
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableHeartBeat }}
          - alert: HeartBeat
            annotations:
              description: There are no new metrics in monitoring for {{ include "helmMonitorie.name" . }}.
              summary: There are no new metrics in monitoring for {{ include "helmMonitorie.name" . }}.
            expr: conveior_hwHeartbeat{entity="{{ include "helmMonitorie.name" . }}"} == conveior_hwHeartbeat{entity="{{ include "helmMonitorie.name" . }}"} offset 5m
            for: 15m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableDiskUsage }}
          - alert: DiskUsage
            annotations:
              description: There is one disk with capacity used higher than 90% {{ "{{" }} $value }} for {{ include "helmMonitorie.name" . }}.
              summary: There is one disk with capacity used higher than 90% {{ "{{" }} $value }} for {{ include "helmMonitorie.name" . }}.
            expr: conveior_hwDisk{entity="{{ include "helmMonitorie.name" . }}"} > 90
            for: 1m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableNoSWAP }}
          - alert: NoSWAP
            annotations:
              description: There is SWAP not enabled or too low for {{ include "helmMonitorie.name" . }}.
              summary: There is SWAP not enabled or too low for {{ include "helmMonitorie.name" . }}.
            expr: (conveior_hwSwap{entity="{{ include "helmMonitorie.name" . }}",label_name="total"} or on() vector(0)) < 524288000
            for: 1m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableHighSwapUsage }}
          - alert: HighSwapUsage
            annotations:
              description: High Swap Usage Detected {{ include "helmMonitorie.name" . }}.
              summary: High Swap Usage Detected {{ include "helmMonitorie.name" . }}.
            expr: conveior_hwSwap{entity="{{ include "helmMonitorie.name" . }}",label_name="used"} / conveior_hwSwap{entity="{{ include "helmMonitorie.name" . }}",label_name="total"} > 0.80
            for: 1m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableContainerDown }}
          - alert: ContainerDown
            annotations:
              description: There is container down for {{ include "helmMonitorie.name" . }}.
              summary: There is container down for {{ include "helmMonitorie.name" . }}.
            expr: conveior_dockerContainer{entity="{{ include "helmMonitorie.name" . }}"} > 2
            for: 1m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableElasticSearchIndices }}
          - alert: ElasticSearchIndices
            annotations:
              description: There are {{ "{{" }} $value }} Elasticsearch red indices for {{ include "helmMonitorie.name" . }}.
              summary: There are {{ "{{" }} $value }} Elasticsearch red indices for {{ include "helmMonitorie.name" . }}.
            expr: conveior_elasticsearch{entity="{{ include "helmMonitorie.name" . }}",label_name="red"} > 0
            for: 1m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableLokiErrors }}
          - alert: LokiErrors
            expr: rate(loki_error_rate[1m]) > 1
            for: 1m
            labels:
              severity: info
            annotations:
              summary: "There are {{ "{{" }} $value }} Loki errors for {{ include "helmMonitorie.name" . }}."
              description: "There are {{ "{{" }} $value }} Loki errors for {{ include "helmMonitorie.name" . }}."
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableLokiHighErrors }}
          - alert: LokiErrors
            expr: rate(loki_error_rate[5m]) > 5
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "There are {{ "{{" }} $value }} Loki high errors for {{ include "helmMonitorie.name" . }}."
              description: "There are {{ "{{" }} $value }} Loki high errors for {{ include "helmMonitorie.name" . }}."
  {{- end  }}
  {{ end }}