{{ if eq .Values.prometheus.rulesSystem.enabled true -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rules
  namespace: {{ .Release.Namespace }}
data:
  rule-system.yaml: |-
    groups:
      - name: dashboard
        rules:
  {{- if .Values.prometheus.rulesSystem.enableCertificateExpirySoon }}
          - alert: CertificateExpirySoon
            expr: probe_ssl_earliest_cert_expiry - time() < 86400
            for: 10m
            labels:
              severity: critical
            annotations:
              title: "Certificate Expiry Alert"
              description: "The SSL certificate is expiring in less than 24 hours."
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableHeartBeat }}
          - alert: HeartBeat
            annotations:
              description: "{{ include "helmMonitorie.name" . }} - missing metrics"
              summary: "{{ include "helmMonitorie.name" . }} - missing metrics"
            expr: absent(conveior_hwHeartbeat{entity="{{ include "helmMonitorie.name" . }}"}) == 1
            for: 15m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableDiskUsage }}
          - alert: DiskUsage
            annotations:
              description: "{{ include "helmMonitorie.name" . }} - usage ({{ "{{" }} $value }}%)"
              summary: "{{ include "helmMonitorie.name" . }} - usage ({{ "{{" }} $value }}%)"
            expr: 100 - ((node_filesystem_avail_bytes{entity="{{ include "helmMonitorie.name" . }}"} * 100) / node_filesystem_size_bytes{entity="{{ include "helmMonitorie.name" . }}"}) > 90
            for: 5m
            labels:
              severity: warning
  {{- end }}
  {{- if .Values.prometheus.rulesSystem.enableNoSWAP }}
          - alert: NoSWAP
            annotations:
              description: "{{ include "helmMonitorie.name" . }}"
              summary: "{{ include "helmMonitorie.name" . }}"
            expr: node_memory_SwapTotal_bytes{entity="{{ include "helmMonitorie.name" . }}"} / 1024 / 1024 / 1024 < 4            
            for: 10m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableHighSwapUsage }}
          - alert: HighSwapUsage
            annotations:
              description: "{{ include "helmMonitorie.name" . }} - High Swap Usage"
              summary: "{{ include "helmMonitorie.name" . }} - High Swap Usage"
            expr: (node_memory_SwapTotal_bytes{entity="{{ include "helmMonitorie.name" . }}"} - node_memory_SwapFree_bytes{entity="{{ include "helmMonitorie.name" . }}"}) / node_memory_SwapTotal_bytes{entity="{{ include "helmMonitorie.name" . }}"} > 0.80
            for: 5m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableContainerDown }}
          - alert: ContainerDown
            annotations:
              description: "{{ include "helmMonitorie.name" . }}"
              summary: "{{ include "helmMonitorie.name" . }}"
            expr: conveior_dockerContainer{entity="{{ include "helmMonitorie.name" . }}"} > 2
            for: 5m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableElasticSearchIndices }}
          - alert: ElasticSearchIndices
            annotations:
              description: "{{ include "helmMonitorie.name" . }} - Elastic red indices ({{ "{{" }} $value }})"
              summary: "{{ include "helmMonitorie.name" . }} - Elastic red indices ({{ "{{" }} $value }})"
            expr: conveior_elasticsearch{entity="{{ include "helmMonitorie.name" . }}",label_name="red"} > 0
            for: 5m
            labels:
              severity: warning

          - alert: ElasticsearchIndexWithWriteSuffix
            annotations:
              description: "{{ include "helmMonitorie.name" . }} - Index with _write suffix detected."
              summary: "{{ include "helmMonitorie.name" . }} - Index with _write suffix detected."
            expr: count(conveior_elasticsearch_indices{index=~".*_write"}) > 0
            for: 5m
            labels:
              severity: warning

          - alert: MissingElasticsearchIndex
            annotations:
              description: "{{ include "helmMonitorie.name" . }} - One or more indices are missing for the past 7 days."
              summary: "{{ include "helmMonitorie.name" . }} - One or more indices are missing for the past 7 days."
            expr: |
              (
                (
                  count(elasticsearch_indices{index=~"events-.*"}) < 1 or
                  count(elasticsearch_indices{index=~"pageviews-.*"}) < 1 or
                  count(elasticsearch_indices{index=~"pageviews_progress-.*"}) < 1 or
                  count(elasticsearch_indices{index=~"pageviews_time_spent-.*"}) < 1 or
                  count(elasticsearch_indices{index=~"commerce-.*"}) < 1 or
                  count(elasticsearch_indices{index=~"concurrents_by_browser-.*"}) < 1 or
                  count(elasticsearch_indices{index=~"entities-.*"}) < 1
                ) and
                (
                  time() - timestamp(elasticsearch_indices) < 7 * 24 * 60 * 60
                )
              ) > 0
            for: 15m
            labels:
              severity: warning
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableLokiErrors }}
          - alert: LokiErrors
            expr: rate(loki_error_rate[1m]) > 1
            for: 5m
            labels:
              severity: info
            annotations:
              summary: "{{ include "helmMonitorie.name" . }} - Loki errors ({{ "{{" }} $value }})"
              description: "{{ include "helmMonitorie.name" . }} - Loki errors ({{ "{{" }} $value }})"
  {{- end  }}
  {{- if .Values.prometheus.rulesSystem.enableLokiHighErrors }}
          - alert: LokiErrorsHigh
            expr: rate(loki_error_rate[5m]) > 5
            for: 15m
            labels:
              severity: warning
            annotations:
              summary: "{{ include "helmMonitorie.name" . }} - Loki errors ({{ "{{" }} $value }})"
              description: "{{ include "helmMonitorie.name" . }} - Loki errors ({{ "{{" }} $value }})"
  {{- end  }}
  {{- if .Values.prometheus.extraRules }}
  {{- toYaml .Values.prometheus.extraRules | nindent 10 }}
  {{- end }}
  {{ end }}