apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
  prometheus.env.yaml: |-
    global:
      evaluation_interval: 30s
      scrape_interval: 30s
      external_labels:
        prometheus: {{ include "helmMonitorie.name" . }}/{{ include "helmMonitorie.name" . }}
        prometheus_replica: prometheus-{{ include "helmMonitorie.name" . }}-0
    rule_files:
      - /etc/prometheus/rules/*.yaml
    scrape_configs:
      {{- range $item_name, $item := .Values.blackbox }}
      - job_name: serviceMonitor/{{ include "helmMonitorie.name" $ }}/blackbox-{{ $item_name }}/0
        honor_labels: false
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - sys-monitoring
        scrape_interval: 300s
        scrape_timeout: 30s
        metrics_path: /probe
        params:
          module:
            - {{ $item.module }}
          target:
            - {{ $item.url }}
        scheme: http
        relabel_configs:
          - source_labels:
              - job
            target_label: __tmp_prometheus_job_name
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
            regex: (sys-monitoring-blackbox);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
            regex: (prometheus-blackbox-exporter);true
          - action: keep
            source_labels:
              - __meta_kubernetes_endpoint_port_name
            regex: http
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Node;(.*)
            replacement: ${1}
            target_label: node
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Pod;(.*)
            replacement: ${1}
            target_label: pod
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: service
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: drop
            source_labels:
              - __meta_kubernetes_pod_phase
            regex: (Failed|Succeeded)
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: job
            replacement: ${1}
          - source_labels:
              - __meta_kubernetes_service_label_sys_monitoring_blackbox
            target_label: job
            regex: (.+)
            replacement: ${1}
          - target_label: endpoint
            replacement: http
          - source_labels:
              - __address__
            target_label: __tmp_hash
            modulus: 1
            action: hashmod
          - source_labels:
              - __tmp_hash
            regex: 0
            action: keep
        metric_relabel_configs:
          - source_labels:
              - instance
            target_label: instance
            replacement: {{ $item.url }}
            action: replace
          - source_labels:
              - target
            target_label: target
            replacement: {{ $item_name }}
            action: replace
      {{- end }}
      - job_name: serviceMonitor/{{ include "helmMonitorie.name" . }}/pushgw/0
        honor_labels: true
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - {{ include "helmMonitorie.name" . }}
        metrics_path: /{{ .Values.pushgw.uri }}/metrics
        relabel_configs:
          - source_labels:
              - job
            target_label: __tmp_prometheus_job_name
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
            regex: (pushgw);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
            regex: (prometheus-pushgateway);true
          - action: keep
            source_labels:
              - __meta_kubernetes_endpoint_port_name
            regex: http
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Node;(.*)
            replacement: ${1}
            target_label: node
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Pod;(.*)
            replacement: ${1}
            target_label: pod
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: service
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: drop
            source_labels:
              - __meta_kubernetes_pod_phase
            regex: (Failed|Succeeded)
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: job
            replacement: ${1}
          - target_label: endpoint
            replacement: http
          - source_labels:
              - __address__
            target_label: __tmp_hash
            modulus: 1
            action: hashmod
          - source_labels:
              - __tmp_hash
            regex: 0
            action: keep
        metric_relabel_configs: []
    alerting:
      alert_relabel_configs:
        - action: labeldrop
          regex: prometheus_replica
      alertmanagers:
        - path_prefix: /
          scheme: http
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - {{ include "helmMonitorie.name" . }}
          api_version: v2
          relabel_configs:
            - action: keep
              source_labels:
                - __meta_kubernetes_service_name
              regex: alertmanager-operated
            - action: keep
              source_labels:
                - __meta_kubernetes_endpoint_port_name
              regex: http-web