apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pushgw
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: secret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  rules:
    - host: {{ .Values.pushgw.domain }}
      http:
        paths:
          - backend:
              service:
                name: pushgw
                port:
                  number: 9091
            path: /{{ .Values.pushgw.ingressUri }}
            pathType: Prefix