apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "helmMonitorie.name" . }}-pushgw
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: v1.6.0
  name: pushgw
  namespace: {{ .Release.Namespace }}
