apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-ingress
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch