{{ if eq .Values.secrets.type "vault" -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.secrets.vaultUrl }}
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .Values.secrets.tokenName }}
          key: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: secret
    kind: ClusterSecretStore
  target:
    name: secret
  data:
    - secretKey: auth
      remoteRef:
        key: {{ .Values.vaultPath }}/PUSHGW_PASSWORD_HTPASSWD
        property: value
    - secretKey: objstore.yml
      remoteRef:
        key: {{ .Values.vaultPath }}/objstore.yml
        property: objstore.yml
    - secretKey: alertmanager.yaml
      remoteRef:
        key: {{ .Values.vaultPath }}/alertmanager.yaml
        property: alertmanager.yaml
    - secretKey: slack.tmpl
      remoteRef:
        key: {{ .Values.vaultPath }}/slack.tmpl
        property: slack.tmpl
{{ end }}
