apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "helmMonitorie.name" . }}-prometheus
    app.kubernetes.io/name: {{ include "helmMonitorie.name" . }}-prometheus
    app.kubernetes.io/component: prometheus