apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "helmMonitorie.name" . }}-alertmanager
    app.kubernetes.io/name: {{ include "helmMonitorie.name" . }}-alertmanager
    app.kubernetes.io/component: alertmanager