apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
  name: thanos-query
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      nodePort: null
      port: 9090
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: thanos
  type: ClusterIP
