apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  objstore.yml: |-
    type: s3
    config:
      bucket: {{ .Values.thanos.s3Bucket }}
      endpoint: {{ .Values.thanos.s3Endpoint }}
      access_key: {{ .Values.thanos.s3AccessKey }}
      secret_key: {{ .Values.thanos.s3SecretKey }}
