{
 "title": "Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(conveior_dockerContainer{entity=\"$entity\"}, label_name)"
    }
   },
   {
    "name": "url",
    "query": {
     "query": "label_values(probe_success{prometheus=\"$entity/$entity\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "repeat": "container",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_dockerContainer{entity=\"$entity\",label_name=\"$container\"}[xxx .Values.scrapeInterval }}]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 1 },
   "repeat": "url",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$url\"}",
     "legendFormat": "xxxinstance}}"
    }
   ]
  },
  { "title": "HW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU",
   "type": "stat",
   "description": "CPU load average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwCpu{entity=\"$entity\"}[30s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "RAM load average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwRam{entity=\"$entity\",label_name=\"used\"}[30s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "stat",
   "description": "SWAP load average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwSwap{entity=\"$entity\",label_name=\"used\"}[30s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "description": "Disk usage average in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwDisk{entity=\"$entity\",label_name=\"overlay\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "CPU usage",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "conveior_hwCpu{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "RAM total/used",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "conveior_hwRam{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "SWAP total/used",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "conveior_hwSwap{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Disk used",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "conveior_hwDisk{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "CPU per process > 10 %",
   "type": "stat",
   "description": "CPU load per process in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwCpuProcess{entity=\"$entity\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "RAM per process > 10 %",
   "type": "stat",
   "description": "RAM load per process in selected time frame.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwRamProcess{entity=\"$entity\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "description": "Processes count in last 5 minutes",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwProcess{entity=\"$entity\",label_name=\"conveior\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "Boot time",
   "type": "stat",
   "description": "Boot time",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_hwBoot{entity=\"$entity\"}[30s]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "CPU usage per process > 10%",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "conveior_hwCpuProcess{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "RAM total/used per process > 10",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "conveior_hwRamProcess{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "conveior_hwProcess{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "SQL global_wait_timeout",
   "type": "stat",
   "description": "SQL wait_timeout",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_global_wait_timeout\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "SQL global_interactive_timeout",
   "type": "stat",
   "description": "SQL global_interactive_timeout",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_global_interactive_timeout\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "SQL local_wait_timeout",
   "type": "stat",
   "description": "SQL local_wait_timeout",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_local_wait_timeout\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "SQL local_interactive_timeout",
   "type": "stat",
   "description": "SQL local_interactive_timeout",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_mysql_local_interactive_timeout\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "Sleeper SQL processes",
   "type": "stat",
   "description": "Sleeper SQL processes count in last 5 minutes",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(conveior_sql_query{entity=\"$entity\",query_name=\"conveior_sqlSleeperProcess\"})",
     "legendFormat": "xxxpod}}"
    }
   ]
  },
  {
   "title": "Containers size",
   "type": "stat",
   "description": "Sum of size of containers in last 5 minutes",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(conveior_hwDockerSize{entity=\"$entity\"})",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Sum of network load of all containers in last 5 minutes",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(conveior_hwNetwork{entity=\"$entity\"})",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "Elasticsearch health",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conveior_elasticsearch{entity=\"$entity\"}[30s]",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Containers",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "conveior_sql_query{entity=\"$entity\",query_name=\"conveior_sqlSleeperProcess\"}",
     "legendFormat": "xxxpod}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Containers",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "conveior_hwDockerSize{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Network usage",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "conveior_hwNetwork{entity=\"$entity\",query_name=\"tx\"}",
     "legendFormat": "xxxlabel_name}}"
    },
    {
     "expr": "conveior_hwNetwork{entity=\"$entity\",query_name=\"rx\"}*(-1)",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "conveior_elasticsearch{entity=\"$entity\"}",
     "legendFormat": "xxxlabel_name}}"
    }
   ]
  },
  {
   "title": "Containers, DB, Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers start up time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "targets": [
      {
       "expr": "conveior_hwDockerLs{entity=\"$entity\"}*1000",
       "legendFormat": "xxxlabel_name}}"
      }
     ]
    },
    {
     "title": "Containers size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 13, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "conveior_hwDockerSize{entity=\"$entity\"}",
       "legendFormat": "xxxlabel_name}}"
      }
     ]
    },
    {
     "title": "Containers size",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_hwDockerSize{entity=\"$entity\"}[30s]",
       "legendFormat": "xxxlabel_name}}"
      }
     ]
    },
    {
     "title": "Heartbeat",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "targets": [
      {
       "expr": "conveior_hwHeartbeat{entity=\"$entity\"}*1000",
       "legendFormat": "xxxjob}}"
      }
     ]
    },
    {
     "title": "DB table size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 13, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_dbSize\"}",
       "legendFormat": "xxxlabel_name}}"
      }
     ]
    },
    {
     "title": "DB table size",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conveior_sql_query{entity=\"$entity\", query_name=\"conveior_dbSize\"}[30s]",
       "legendFormat": "xxxlabel_name}}"
      }
     ]
    }
   ]
  }
 ]
}