name: Helm Publish

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.1

      - name: Package Helm Chart
        run: |
          helm package chart
          helm repo index --url https://github.com/lukas-pastva/helm-monitorie --merge index.yaml .

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Update Helm chart and repository index"
          git push

      - name: Upload Helm Package as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: helm-chart
          path: "*.tgz"
