name: Helm Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.1

      - name: Package Helm Chart
        run: |
          helm package chart
          helm repo index --url https://github.com/lukas-pastva/helm-monitorie --merge index.yaml .

      - name: Set Helm Experimental OCI Environment Variable
        run: echo "HELM_EXPERIMENTAL_OCI=1" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT }} | helm registry login -u $GITHUB_ACTOR --password-stdin ghcr.io

      - name: Push Helm Chart to GitHub Packages
        run: |
          helm chart save ./helm-monitorie-*.tgz ghcr.io/lukas-pastva/helm-monitorie:0.1.0
          helm chart push ghcr.io/lukas-pastva/helm-monitorie:0.1.0

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v0.1.0
          release_name: "Helm Chart Release v0.1.0"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./helm-monitorie-*.tgz
          asset_name: helm-monitorie-0.1.0.tgz
          asset_content_type: application/gzip
